---
application:
  name: "garufurendo-backend"
  project: "Telegram Bot Backend"
  organization: "QoveryCommunity"
routers:
- name: "main-garufurendo-backend"
  routes:
  - application_name: "garufurendo-backend"
    paths:
    - "/*"
