---
application:
  name: "garufurendo"
  project: "Telegram Bot"
  organization: "QoveryCommunity"
routers:
- name: "main-garufurendo"
  routes:
  - application_name: "garufurendo"
    paths:
    - "/*"
