---
application:
  name: "garufuren-api"
  project: "bro-pann-garufurendo"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "ガルフレンド"
  version: "4.4"
routers:
- name: "main-garufuren-api"
  routes:
  - application_name: "garufuren-api"
    paths:
    - "/*"
